# fly.toml app configuration file generated for gestor-financiero on 2026-06-27T16:54:47-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'gestor-financiero'
primary_region = 'lax'

[build]
  dockerfile = 'Dockerfile'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '256mb'
  cpus = 1
  memory_mb = 256
